// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packets.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	packets.proto

It has these top-level messages:
	Request
	Response
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Method     string `protobuf:"bytes,1,opt,name=method" json:"method,omitempty"`
	Host       string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	RemoteAddr string `protobuf:"bytes,3,opt,name=remoteAddr" json:"remoteAddr,omitempty"`
	RequestURI string `protobuf:"bytes,4,opt,name=requestURI" json:"requestURI,omitempty"`
	Body       []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Request) GetRequestURI() string {
	if m != nil {
		return m.RequestURI
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Response struct {
	Status int64  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Body   []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
}

func init() { proto.RegisterFile("packets.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0x4c, 0xce,
	0x4e, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xea, 0x64,
	0xe4, 0x62, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0xcb, 0x4d, 0x2d,
	0xc9, 0xc8, 0x4f, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf2, 0x84, 0x84, 0xb8, 0x58,
	0x32, 0xf2, 0x8b, 0x4b, 0x24, 0x98, 0xc0, 0xa2, 0x60, 0xb6, 0x90, 0x1c, 0x17, 0x57, 0x51, 0x6a,
	0x6e, 0x7e, 0x49, 0xaa, 0x63, 0x4a, 0x4a, 0x91, 0x04, 0x33, 0x58, 0x06, 0x49, 0x04, 0x22, 0x0f,
	0x36, 0x36, 0x34, 0xc8, 0x53, 0x82, 0x05, 0x26, 0x0f, 0x13, 0x01, 0x99, 0x99, 0x94, 0x9f, 0x52,
	0x29, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x2b, 0x99, 0x71, 0x71, 0x04, 0xa5, 0x16,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x82, 0xdc, 0x52, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x0c, 0x76, 0x0b,
	0x73, 0x10, 0x94, 0x07, 0xd7, 0xc7, 0x84, 0xd0, 0x97, 0xc4, 0x06, 0xf6, 0x8e, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0x32, 0x1e, 0x7f, 0xdc, 0xdf, 0x00, 0x00, 0x00,
}
